# Description: Dockerfile for development environment
FROM node:20-alpine
# Set metadata
LABEL description="dev environment for web" version="1.0" maintainer="Alan"
# Set working directory
WORKDIR /app
# Environment variables
ENV DEV=true
ENV VITE_API_HOST=http://localhost:8081
ENV VITE_MAPBOX_TOKEN=pk.eyJ1IjoiaHVhbjU2NzgiLCJhIjoiY2xnemhiaHJoMGp1ejNocGN5OXh1NTNsZyJ9.An3ZM8QfarnSBWhBqzV0YQ
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
# Port
EXPOSE 5173
# Copy all files
COPY . ./
# Start the app
CMD ["npm", "run", "dev"]
