import prisma from '../client';
import { imgurClient } from '../../src/helpers/imgurClient.helper';

export async function insertMeals() {
  const categories = await prisma.category.findMany({
    select: {
      id: true,
      title: true,
    },
  });

  const categoryMap = categories.reduce((map, category) => {
    map[category.title] = category.id;
    return map;
  }, {});

  const album = await imgurClient.getAlbum(process.env.IMGUR_ALBUM_ID as string);
  const images = album.data.images.reduce((map, image) => {
    map[image.description as string] = image.id;
    return map;
  }, {});

  const mealData = [
    {
      title: '烤魚下巴',
      price: 180,
      description: '現烤現做需要25分左右',
      isPopular: true,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤魚下巴'],
    },
    {
      title: '秋刀魚',
      price: 180,
      description: '現烤現做需要25分左右',
      isPopular: false,
      categoryId: categoryMap['火烤類'],
      imageId: images['秋刀魚'],
    },
    {
      title: '烤日式鯖魚',
      price: 180,
      description: '現烤現做需要25分左右',
      isPopular: true,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤日式鯖魚'],
    },
    {
      title: '鹽豬肉',
      price: 210,
      description: '現烤現做需要25分左右\n肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['火烤類'],
      imageId: images['鹽豬肉'],
    },
    {
      title: '牛小排',
      price: 220,
      description: '現烤現做需要25分左右',
      isPopular: true,
      categoryId: categoryMap['火烤類'],
      imageId: images['牛小排'],
    },
    {
      title: '烤松阪豬肉',
      price: 270,
      description: '現烤現做需要25分左右\n肉品原產地：西班牙豬肉',
      isPopular: true,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤松阪豬肉'],
    },
    {
      title: '烤櫻桃鴨肉串(4串)',
      price: 230,
      description: '現烤現做需要25分左右',
      isPopular: false,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤櫻桃鴨肉串(4串)'],
    },
    {
      title: '安格斯牛小排',
      price: 520,
      description: '',
      isPopular: false,
      categoryId: categoryMap['火烤類'],
      imageId: images['安格斯牛小排'],
    },
    {
      title: '烤鮭魚肚',
      price: 320,
      description: '約250g',
      isPopular: true,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤鮭魚肚'],
    },
    {
      title: '烤鮭魚頭(半顆)',
      price: 350,
      description: '',
      isPopular: false,
      categoryId: categoryMap['火烤類'],
      imageId: images['烤鮭魚頭(半顆)'],
    },
    {
      title: '港都海產鍋(大)',
      price: 1100,
      description: '使用產銷履歷鱸魚\n此餐點需要25分以上',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['港都海產鍋(大)'],
    },
    {
      title: '港都海產鍋(小)',
      price: 600,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['港都海產鍋(小)'],
    },
    {
      title: '生綠竹筍雞鍋(大)',
      price: 800,
      description: '使用產銷履歷雞肉\n生綠竹筍為季節限定',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['生綠竹筍雞鍋(大)'],
    },
    {
      title: '生綠竹筍雞鍋(小)',
      price: 480,
      description: '使用產銷履歷雞肉\n生綠竹筍為季節限定',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['生綠竹筍雞鍋(小)'],
    },
    {
      title: '鰱魚頭鍋(大)',
      price: 1100,
      description: '',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['鰱魚頭鍋(大)'],
    },
    {
      title: '鰱魚頭鍋(小)',
      price: 600,
      description: '',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['鰱魚頭鍋(小)'],
    },
    {
      title: '鳳梨苦瓜雞鍋(大)',
      price: 800,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['鳳梨苦瓜雞鍋(大)'],
    },
    {
      title: '鳳梨苦瓜雞鍋(小)',
      price: 480,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['鳳梨苦瓜雞鍋(小)'],
    },
    {
      title: '陳年菜甫雞鍋(大)',
      price: 800,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['陳年菜甫雞鍋(大)'],
    },
    {
      title: '陳年菜甫雞鍋(小)',
      price: 480,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['陳年菜甫雞鍋(小)'],
    },
    {
      title: '養生百菇雞鍋(大)',
      price: 980,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['養生百菇雞鍋(大)'],
    },
    {
      title: '養生百菇雞鍋(小)',
      price: 565,
      description: '使用產銷履歷雞肉',
      isPopular: false,
      categoryId: categoryMap['火鍋類'],
      imageId: images['養生百菇雞鍋(小)'],
    },
    {
      title: '肉絲炒飯',
      price: 110,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['肉絲炒飯'],
    },
    {
      title: '肉絲炒麵',
      price: 110,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['肉絲炒麵'],
    },
    {
      title: '牛肉炒飯',
      price: 135,
      description: '',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['牛肉炒飯'],
    },
    {
      title: '牛肉炒麵',
      price: 135,
      description: '',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['牛肉炒麵'],
    },
    {
      title: '羊肉炒飯',
      price: 135,
      description: '',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['羊肉炒飯'],
    },
    {
      title: '羊肉炒麵',
      price: 135,
      description: '',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['羊肉炒麵'],
    },
    {
      title: '蝦仁炒飯',
      price: 150,
      description: '使用產銷履歷白蝦',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['蝦仁炒飯'],
    },
    {
      title: '蝦仁炒麵',
      price: 150,
      description: '使用產銷履歷白蝦',
      isPopular: false,
      categoryId: categoryMap['飯麵類'],
      imageId: images['蝦仁炒麵'],
    },
    {
      title: '沙茶炒羊肉',
      price: 195,
      description: '一般會用空心菜，用完會改用高麗菜。',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['沙茶炒羊肉'],
    },
    {
      title: '沙茶炒牛肉',
      price: 195,
      description: '一般會用空心菜，用完會改用高麗菜。',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['沙茶炒牛肉'],
    },
    {
      title: '蔥爆牛肉',
      price: 220,
      description: '肉品原產地：澳洲',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['蔥爆牛肉'],
    },
    {
      title: '糖醋排骨',
      price: 190,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['糖醋排骨'],
    },
    {
      title: '糖醋里肌',
      price: 190,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['糖醋里肌'],
    },
    {
      title: '炒回鍋肉',
      price: 195,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['炒回鍋肉'],
    },
    {
      title: '蒜泥白肉',
      price: 190,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['蒜泥白肉'],
    },
    {
      title: '宮保雞丁',
      price: 190,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['宮保雞丁'],
    },
    {
      title: '橙汁排骨',
      price: 190,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒肉類'],
      imageId: images['橙汁排骨'],
    },
    {
      title: '地芋肥腸',
      price: 250,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['地芋肥腸'],
    },
    {
      title: '蒼蠅頭',
      price: 180,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['蒼蠅頭'],
    },
    {
      title: '鹹蛋炒苦瓜',
      price: 180,
      description: '使用產銷履歷苦瓜',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['鹹蛋炒苦瓜'],
    },
    {
      title: '鹹蛋炒竹筍',
      price: 195,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['鹹蛋炒竹筍'],
    },
    {
      title: '蚵仔炒蛋',
      price: 210,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['蚵仔炒蛋'],
    },
    {
      title: '蝦仁炒蛋',
      price: 240,
      description: '使用產銷履歷白蝦',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['蝦仁炒蛋'],
    },
    {
      title: '菜脯炒蛋',
      price: 160,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['菜脯炒蛋'],
    },
    {
      title: '客家小炒',
      price: 195,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['客家小炒'],
    },
    {
      title: '丁香炒花生',
      price: 200,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['丁香炒花生'],
    },
    {
      title: '老皮嫩肉',
      price: 200,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['老皮嫩肉'],
    },
    {
      title: '麻婆豆腐',
      price: 180,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['麻婆豆腐'],
    },
    {
      title: '紅燒豆腐',
      price: 180,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['紅燒豆腐'],
    },
    {
      title: '蟹黃豆腐',
      price: 190,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['蟹黃豆腐'],
    },
    {
      title: '四季肥腸',
      price: 250,
      description: '肉品原產地：歐洲豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['四季肥腸'],
    },
    {
      title: '薑絲大腸',
      price: 190,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['薑絲大腸'],
    },
    {
      title: '麻油腰花',
      price: 280,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['麻油腰花'],
    },
    {
      title: '蠔油豬肝',
      price: 180,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['蠔油豬肝'],
    },
    {
      title: '絲瓜蛤仔',
      price: 240,
      description: '使用產銷履歷絲瓜',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['絲瓜蛤仔'],
    },
    {
      title: 'XO將頻果炒生干貝',
      price: 390,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒什錦類'],
      imageId: images['XO將頻果炒生干貝'],
    },
    {
      title: '白灼(燙)蝦',
      price: 320,
      description: '使用產銷履歷蝦',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['白灼(燙)蝦'],
    },
    {
      title: '芹菜炒花枝',
      price: 240,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['芹菜炒花枝'],
    },
    {
      title: '川燙透抽',
      price: 380,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['川燙透抽'],
    },
    {
      title: '塔香炒螺肉',
      price: 180,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['塔香炒螺肉'],
    },
    {
      title: '炒海瓜子',
      price: 250,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['炒海瓜子'],
    },
    {
      title: '蒜泥大草蝦',
      price: 450,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['蒜泥大草蝦'],
    },
    {
      title: '蒜泥蚵仔',
      price: 210,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['蒜泥蚵仔'],
    },
    {
      title: '生炒三鮮',
      price: 230,
      description: '(水鯊、花枝、魷魚)',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['生炒三鮮'],
    },
    {
      title: '泰式檸檬鱸魚',
      price: 430,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['泰式檸檬鱸魚'],
    },
    {
      title: '泰式檸檬蝦',
      price: 450,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['泰式檸檬蝦'],
    },
    {
      title: '清蒸鱈魚',
      price: 300,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['清蒸鱈魚'],
    },
    {
      title: '豆酥鱈魚',
      price: 300,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['豆酥鱈魚'],
    },
    {
      title: '橙汁鱸魚片',
      price: 240,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['橙汁鱸魚片'],
    },
    {
      title: '糖醋鱸魚片',
      price: 240,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['糖醋鱸魚片'],
    },
    {
      title: '蔥燒炒蟹',
      price: 450,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['蔥燒炒蟹'],
    },
    {
      title: '避風塘炒蟹',
      price: 450,
      description: '',
      isPopular: true,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['避風塘炒蟹'],
    },
    {
      title: '炒蛤仔',
      price: 190,
      description: '',
      isPopular: false,
      categoryId: categoryMap['熱炒海鮮類'],
      imageId: images['炒蛤仔'],
    },
    {
      title: '泰式椒麻雞',
      price: 250,
      description: '',
      isPopular: true,
      categoryId: categoryMap['酥炸類'],
      imageId: images['泰式椒麻雞'],
    },
    {
      title: '鹽酥蝦',
      price: 280,
      description: '使用產銷履歷蝦',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['鹽酥蝦'],
    },
    {
      title: '鹽酥龍珠',
      price: 210,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['鹽酥龍珠'],
    },
    {
      title: '鳳梨蝦球',
      price: 290,
      description: '',
      isPopular: true,
      categoryId: categoryMap['酥炸類'],
      imageId: images['鳳梨蝦球'],
    },
    {
      title: '脆皮炸肥腸',
      price: 225,
      description: '肉品原產地：歐洲豬肉',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['脆皮炸肥腸'],
    },
    {
      title: '蚵仔酥',
      price: 210,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['蚵仔酥'],
    },
    {
      title: '椒鹽大草蝦',
      price: 450,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['椒鹽大草蝦'],
    },
    {
      title: '五味炸豆腐',
      price: 150,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['五味炸豆腐'],
    },
    {
      title: '酥炸三鮮(蝦仁、花枝、蚵仔)',
      price: 300,
      description: '使用產銷履歷白蝦',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['酥炸三鮮(蝦仁、花枝、蚵仔)'],
    },
    {
      title: '酥炸絲瓜',
      price: 180,
      description: '使用產銷履歷絲瓜',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['酥炸絲瓜'],
    },
    {
      title: '爆漿熔岩蝦球(7粒)',
      price: 270,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['爆漿熔岩蝦球(7粒)'],
    },
    {
      title: '鹽酥中卷',
      price: 280,
      description: '',
      isPopular: false,
      categoryId: categoryMap['酥炸類'],
      imageId: images['鹽酥中卷'],
    },
    {
      title: '三杯雞',
      price: 250,
      description: '',
      isPopular: true,
      categoryId: categoryMap['三杯類'],
      imageId: images['三杯雞'],
    },
    {
      title: '三杯中卷',
      price: 280,
      description: '',
      isPopular: true,
      categoryId: categoryMap['三杯類'],
      imageId: images['三杯中卷'],
    },
    {
      title: '三杯豬肝',
      price: 200,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['三杯類'],
      imageId: images['三杯豬肝'],
    },
    {
      title: '三杯皮蛋',
      price: 200,
      description: '',
      isPopular: false,
      categoryId: categoryMap['三杯類'],
      imageId: images['三杯皮蛋'],
    },
    {
      title: '三杯田雞',
      price: 300,
      description: '',
      isPopular: false,
      categoryId: categoryMap['三杯類'],
      imageId: images['三杯田雞'],
    },
    {
      title: '鐵板牛柳',
      price: 280,
      description: '肉品原產地：澳洲',
      isPopular: true,
      categoryId: categoryMap['鐵板類'],
      imageId: images['鐵板牛柳'],
    },
    {
      title: '鐵板豆腐',
      price: 230,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['鐵板類'],
      imageId: images['鐵板豆腐'],
    },
    {
      title: '鐵板蚵仔',
      price: 250,
      description: '',
      isPopular: false,
      categoryId: categoryMap['鐵板類'],
      imageId: images['鐵板蚵仔'],
    },
    {
      title: '鐵板豬肝',
      price: 200,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['鐵板類'],
      imageId: images['鐵板豬肝'],
    },
    {
      title: '五更腸旺',
      price: 250,
      description: '肉品原產地：歐洲豬肉',
      isPopular: true,
      categoryId: categoryMap['煲類'],
      imageId: images['五更腸旺'],
    },
    {
      title: '茄子腸煲',
      price: 270,
      description: '肉品原產地：歐洲豬肉',
      isPopular: false,
      categoryId: categoryMap['煲類'],
      imageId: images['茄子腸煲'],
    },
    {
      title: '茄子雞煲',
      price: 280,
      description: '',
      isPopular: false,
      categoryId: categoryMap['煲類'],
      imageId: images['茄子雞煲'],
    },
    {
      title: '花雕雞煲',
      price: 300,
      description: '',
      isPopular: true,
      categoryId: categoryMap['煲類'],
      imageId: images['花雕雞煲'],
    },
    {
      title: '炒高麗菜',
      price: 135,
      description: '豬脂(油)原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['青菜類'],
      imageId: images['炒高麗菜'],
    },
    {
      title: '炒空心菜',
      price: 135,
      description: '豬脂(油)原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['炒空心菜'],
    },
    {
      title: '炒水蓮菜',
      price: 180,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['炒水蓮菜'],
    },
    {
      title: '杞子炒川七',
      price: 160,
      description: '',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['杞子炒川七'],
    },
    {
      title: '紅燒茄子',
      price: 160,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['紅燒茄子'],
    },
    {
      title: '皮蛋地瓜葉',
      price: 195,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['皮蛋地瓜葉'],
    },
    {
      title: '燙地瓜葉',
      price: 160,
      description: '肉品原產地：臺灣豬肉',
      isPopular: true,
      categoryId: categoryMap['青菜類'],
      imageId: images['燙地瓜葉'],
    },
    {
      title: '乾煸四季豆',
      price: 185,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['乾煸四季豆'],
    },
    {
      title: '炒菠菜',
      price: 150,
      description: '',
      isPopular: false,
      categoryId: categoryMap['青菜類'],
      imageId: images['炒菠菜'],
    },
    {
      title: '薑絲鱸魚湯(大)',
      price: 380,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['薑絲鱸魚湯(大)'],
    },
    {
      title: '薑絲鱸魚湯(中)',
      price: 200,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['薑絲鱸魚湯(中)'],
    },
    {
      title: '薑絲鱸魚湯(小)',
      price: 110,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['薑絲鱸魚湯(小)'],
    },
    {
      title: '味噌鱸魚湯(大)',
      price: 380,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['味噌鱸魚湯(大)'],
    },
    {
      title: '味噌鱸魚湯(中)',
      price: 200,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['味噌鱸魚湯(中)'],
    },
    {
      title: '味噌鱸魚湯(小)',
      price: 110,
      description: '使用產銷履歷鱸魚',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['味噌鱸魚湯(小)'],
    },
    {
      title: '蛤蠣湯(大)',
      price: 355,
      description: '',
      isPopular: true,
      categoryId: categoryMap['湯類'],
      imageId: images['蛤蠣湯(大)'],
    },
    {
      title: '蛤蠣湯(中)',
      price: 185,
      description: '',
      isPopular: true,
      categoryId: categoryMap['湯類'],
      imageId: images['蛤蠣湯(中)'],
    },
    {
      title: '蛤蠣湯(小)',
      price: 100,
      description: '',
      isPopular: true,
      categoryId: categoryMap['湯類'],
      imageId: images['蛤蠣湯(小)'],
    },
    {
      title: '蚵仔湯(大)',
      price: 355,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['蚵仔湯(大)'],
    },
    {
      title: '蚵仔湯(中)',
      price: 185,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['蚵仔湯(中)'],
    },
    {
      title: '蚵仔湯(小)',
      price: 100,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['蚵仔湯(小)'],
    },
    {
      title: '豬肝湯(大)',
      price: 260,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['豬肝湯(大)'],
    },
    {
      title: '豬肝湯(中)',
      price: 130,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['豬肝湯(中)'],
    },
    {
      title: '豬肝湯(小)',
      price: 80,
      description: '肉品原產地：臺灣豬肉',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['豬肝湯(小)'],
    },
    {
      title: '番茄豆腐蛋花湯(大)',
      price: 260,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['番茄豆腐蛋花湯(大)'],
    },
    {
      title: '番茄豆腐蛋花湯(中)',
      price: 130,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['番茄豆腐蛋花湯(中)'],
    },
    {
      title: '番茄豆腐蛋花湯(小)',
      price: 80,
      description: '',
      isPopular: false,
      categoryId: categoryMap['湯類'],
      imageId: images['番茄豆腐蛋花湯(小)'],
    },
    {
      title: '白飯',
      price: 20,
      description: '168g，每滿＄200有贈送1碗白飯(不包含炒飯麵、白飯及運費)，請再結帳頁面的附註上說明。這邊提供額外加點的服務',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['白飯'],
    },
    {
      title: '小菜毛豆',
      price: 50,
      description: '',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['小菜毛豆'],
    },
    {
      title: '聖沛黎洛 天然氣泡水',
      price: 100,
      description: '750ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['聖沛黎洛 天然氣泡水'],
    },
    {
      title: '老北京御品酸梅湯',
      price: 100,
      description: '900ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['老北京御品酸梅湯'],
    },
    {
      title: '愛之味麥仔茶',
      price: 60,
      description: '990ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['愛之味麥仔茶'],
    },
    {
      title: '御茶園日式綠茶',
      price: 60,
      description: '980ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['御茶園日式綠茶'],
    },
    {
      title: '蘋果西打',
      price: 50,
      description: '600ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['蘋果西打'],
    },
    {
      title: '可口可樂',
      price: 50,
      description: '600ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['可口可樂'],
    },
    {
      title: '半天水椰子汁',
      price: 70,
      description: '520ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['半天水椰子汁'],
    },
    {
      title: '泰山冰鎮紅茶',
      price: 60,
      description: '900ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['泰山冰鎮紅茶'],
    },
    {
      title: '優鮮沛蔓越莓',
      price: 60,
      description: '900ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['優鮮沛蔓越莓'],
    },
    {
      title: 'Sunkist芭樂汁',
      price: 60,
      description: '900ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['Sunkist芭樂汁'],
    },
    {
      title: 'Sunkist柳橙汁',
      price: 60,
      description: '900ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['Sunkist柳橙汁'],
    },
    {
      title: '蜂蜜檸檬(小)',
      price: 130,
      description: '500ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['蜂蜜檸檬(小)'],
    },
    {
      title: '蜂蜜檸檬(大)',
      price: 200,
      description: '800ml',
      isPopular: false,
      categoryId: categoryMap['單點及無酒精飲料'],
      imageId: images['蜂蜜檸檬(大)'],
    },
  ];

  return await prisma.meal.createMany({
    data: mealData,
  });

  // const sqlInsertValues = mealData.map((m) => {
  //   const imageId = images[m.title] as string;
  //   const categoryId = categoryMap[m.categoryId];

  //   return prisma.$executeRaw`
  //     INSERT INTO
  //       meals (title, price, image_id, description, is_popular, category_id)
  //     VALUES (
  //       ${m.title},
  //       ${m.price},
  //       ${imageId},
  //       ${m.description},
  //       ${m.isPopular},
  //       ${m.categoryId}
  //       imageId: images[]
  //     );
  //   `;
  // });

  // return prisma.$transaction([
  //   prisma.$executeRaw`
  //     DELETE FROM meals;
  //   `,
  //   ...sqlInsertValues,
  //   // prisma.$executeRaw`
  //   //   DO $$
  //   //   DECLARE
  //   //     claypot_id UUID;
  //   //     stir_fried_assorted_id UUID;
  //   //     iron_plate_id UUID;
  //   //     rice_noodles_id UUID;
  //   //     hot_pot_id UUID;
  //   //     fire_roasted_id UUID;
  //   //     stir_fried_meat_id UUID;
  //   //     stir_fired_seafood_id UUID;
  //   //     soup_id UUID;
  //   //     deep_fried_id UUID;
  //   //     three_cups_id UUID;
  //   //     vegetables_id UUID;
  //   //     a_la_carte_non_alcoholic_id UUID;
  //   //   BEGIN
  //   //   SELECT id INTO claypot_id FROM categories WHERE title = '煲類';
  //   //   SELECT id INTO stir_fried_assorted_id FROM categories WHERE title = '熱炒什錦類';
  //   //   SELECT id INTO iron_plate_id FROM categories WHERE title = '鐵板類';
  //   //   SELECT id INTO rice_noodles_id FROM categories WHERE title = '飯麵類';
  //   //   SELECT id INTO hot_pot_id FROM categories WHERE title = '火鍋類';
  //   //   SELECT id INTO fire_roasted_id FROM categories WHERE title = '火烤類';
  //   //   SELECT id INTO stir_fried_meat_id FROM categories WHERE title = '熱炒肉類';
  //   //   SELECT id INTO stir_fired_seafood_id FROM categories WHERE title = '熱炒海鮮類';
  //   //   SELECT id INTO soup_id FROM categories WHERE title = '湯類';
  //   //   SELECT id INTO deep_fried_id FROM categories WHERE title = '酥炸類';
  //   //   SELECT id INTO three_cups_id FROM categories WHERE title = '三杯類';
  //   //   SELECT id INTO vegetables_id FROM categories WHERE title = '青菜類';
  //   //   SELECT id INTO a_la_carte_non_alcoholic_id FROM categories WHERE title = '單點及無酒精飲料';

  //   //   INSERT INTO
  //   //   meals (title, price, image_id, image_delete_hash, description, is_popular, category_id)
  //   //   VALUES
  //   //     ('烤魚下巴', 180, 'AP4WZzq', '現烤現做需要25分左右', TRUE, fire_roasted_id),
  //   //     ('秋刀魚', 180, 'LfOf1Xh', '現烤現做需要25分左右', FALSE, fire_roasted_id),
  //   //     ('烤日式鯖魚', 180, 'eBJF90b', '現烤現做需要25分左右', TRUE, fire_roasted_id),
  //   //     ('鹽豬肉', 210, 'rj0SrQ3', '現烤現做需要25分左右\n肉品原產地：臺灣豬肉', FALSE, fire_roasted_id),
  //   //     ('牛小排', 220, 'sLkPG59', '現烤現做需要25分左右', TRUE, fire_roasted_id),
  //   //     ('烤松阪豬肉', 270, 'ZqKz6Bs', '現烤現做需要25分左右\n肉品原產地：西班牙豬肉', TRUE, fire_roasted_id),
  //   //     ('烤櫻桃鴨肉串(4串)', 230, 'Rx7Yi5n', '現烤現做需要25分左右', FALSE, fire_roasted_id),
  //   //     ('安格斯牛小排', 520, 'JfaOfU7', '', FALSE, fire_roasted_id),
  //   //     ('烤鮭魚肚', 320, 'B8usWoR', '約250g', TRUE, fire_roasted_id),
  //   //     ('烤鮭魚頭(半顆)', 350, 'VOP4nqc', '', FALSE, fire_roasted_id),
  //   //     ('港都海產鍋(大)', 1100, 'JGoIzWk', '使用產銷履歷鱸魚\n此餐點需要25分以上', FALSE, hot_pot_id),
  //   //     ('港都海產鍋(小)', 600, 'Bgq4aUp', '使用產銷履歷鱸魚', FALSE, hot_pot_id),
  //   //     ('生綠竹筍雞鍋(大)', 800, 'HXoeGLw', '使用產銷履歷雞肉\n生綠竹筍為季節限定', FALSE, hot_pot_id),
  //   //     ('生綠竹筍雞鍋(小)', 480, 'wN4JZMj', '使用產銷履歷雞肉\n生綠竹筍為季節限定', FALSE, hot_pot_id),
  //   //     ('鰱魚頭鍋(大)', 1100, '2rBX4gj', '', FALSE, hot_pot_id),
  //   //     ('鰱魚頭鍋(小)', 600, 'b4pTASb', '', FALSE, hot_pot_id),
  //   //     ('鳳梨苦瓜雞鍋(大)', 800, '3dRAW1z', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('鳳梨苦瓜雞鍋(小)', 480, '7QlmizD', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('陳年菜甫雞鍋(大)', 800, 'VGAhrWg', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('陳年菜甫雞鍋(小)', 480, 'FSD7LYw', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('養生百菇雞鍋(大)', 980, 'jqIpyBt', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('養生百菇雞鍋(小)', 565, 'VeiBp44', '使用產銷履歷雞肉', FALSE, hot_pot_id),
  //   //     ('肉絲炒飯', 110, 'QLiKO3z', '肉品原產地：臺灣豬肉', FALSE, rice_noodles_id),
  //   //     ('肉絲炒麵', 110, 'kqsBv63', '肉品原產地：臺灣豬肉', FALSE, rice_noodles_id),
  //   //     ('牛肉炒飯', 135, 'pF2faYj', '', FALSE, rice_noodles_id),
  //   //     ('牛肉炒麵', 135, 'RC8c4S3', '', FALSE, rice_noodles_id),
  //   //     ('羊肉炒飯', 135, 'IiqS3Rt', '', FALSE, rice_noodles_id),
  //   //     ('羊肉炒麵', 135, 'xUmjZ63', '', FALSE, rice_noodles_id),
  //   //     ('蝦仁炒飯', 150, 'Oftqm6P', '使用產銷履歷白蝦', FALSE, rice_noodles_id),
  //   //     ('蝦仁炒麵', 150, 'XJHsvfr', '使用產銷履歷白蝦', FALSE, rice_noodles_id),
  //   //     ('沙茶炒羊肉', 195, 'wXGCT2L', '一般會用空心菜，用完會改用高麗菜。', FALSE, stir_fried_meat_id),
  //   //     ('沙茶炒牛肉', 195, 'Ychaati', '一般會用空心菜，用完會改用高麗菜。', FALSE, stir_fried_meat_id),
  //   //     ('蔥爆牛肉', 220, 'JG0QD3r', '肉品原產地：澳洲', FALSE, stir_fried_meat_id),
  //   //     ('糖醋排骨', 190, 'KR4mVZi', '肉品原產地：臺灣豬肉', FALSE, stir_fried_meat_id),
  //   //     ('糖醋里肌', 190, '1fZhWFc', '肉品原產地：臺灣豬肉', TRUE, stir_fried_meat_id),
  //   //     ('炒回鍋肉', 195, 'tE83vvl', '肉品原產地：臺灣豬肉', TRUE, stir_fried_meat_id),
  //   //     ('蒜泥白肉', 190, 'PeRhaiI', '肉品原產地：臺灣豬肉', FALSE, stir_fried_meat_id),
  //   //     ('宮保雞丁', 190, '2s160Vz', '', TRUE, stir_fried_meat_id),
  //   //     ('橙汁排骨', 190, 'mmblsMc', '肉品原產地：臺灣豬肉', FALSE, stir_fried_meat_id),
  //   //     ('地芋肥腸', 250, 'YgtgRvj', '肉品原產地：臺灣豬肉', TRUE, stir_fried_assorted_id),
  //   //     ('蒼蠅頭', 180, 'XDzkgDV', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('鹹蛋炒苦瓜', 180, 'oO5N8kh', '使用產銷履歷苦瓜', FALSE, stir_fried_assorted_id),
  //   //     ('鹹蛋炒竹筍', 195, 'BLhkuIa', '', FALSE, stir_fried_assorted_id),
  //   //     ('蚵仔炒蛋', 210, '20s7o39', '', FALSE, stir_fried_assorted_id),
  //   //     ('蝦仁炒蛋', 240, 'ObqjQNI', '使用產銷履歷白蝦', FALSE, stir_fried_assorted_id),
  //   //     ('菜脯炒蛋', 160, '8kDnLXB', '', FALSE, stir_fried_assorted_id),
  //   //     ('客家小炒', 195, 'VxZbsa1', '肉品原產地：臺灣豬肉', TRUE, stir_fried_assorted_id),
  //   //     ('丁香炒花生', 200, 'eC2gJtj', '', FALSE, stir_fried_assorted_id),
  //   //     ('老皮嫩肉', 200, 'hQPDj5w', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('麻婆豆腐', 180, '2jqudNh', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('紅燒豆腐', 180, 'F10WgLr', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('蟹黃豆腐', 190, 'fGmYzCd', '', FALSE, stir_fried_assorted_id),
  //   //     ('四季肥腸', 250, 'fLgHgDm', '肉品原產地：歐洲豬肉', TRUE, stir_fried_assorted_id),
  //   //     ('薑絲大腸', 190, 'p3mlWLp', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('麻油腰花', 280, 'YLBdPQG', '肉品原產地：臺灣豬肉', TRUE, stir_fried_assorted_id),
  //   //     -- ('蠔油豬肝', 180, 'ax1lvjz', '肉品原產地：臺灣豬肉', FALSE, stir_fried_assorted_id),
  //   //     ('絲瓜蛤仔', 240, '71tKLB3', '使用產銷履歷絲瓜', FALSE, stir_fried_assorted_id),
  //   //     ('XO將頻果炒生干貝', 390, 'fYoJS5s', '', FALSE, stir_fried_assorted_id),
  //   //     ('白灼(燙)蝦', 320, '27MzfMA', '使用產銷履歷蝦', FALSE, stir_fired_seafood_id),
  //   //     ('芹菜炒花枝', 240, 'IA8CHtu', '', FALSE, stir_fired_seafood_id),
  //   //     ('川燙透抽', 380, 'PIHmUgI', '', TRUE, stir_fired_seafood_id),
  //   //     ('塔香炒螺肉', 180, 'anyVTyB', '', FALSE, stir_fired_seafood_id),
  //   //     ('炒海瓜子', 250, 'JT7X9i8', '', TRUE, stir_fired_seafood_id),
  //   //     ('蒜泥大草蝦', 450, 'q4Acy23', '', FALSE, stir_fired_seafood_id),
  //   //     ('蒜泥蚵仔', 210, '8EzZ15F', '', FALSE, stir_fired_seafood_id),
  //   //     ('生炒三鮮', 230, '0DEDOtI', '(水鯊、花枝、魷魚)', FALSE, stir_fired_seafood_id),
  //   //     ('泰式檸檬鱸魚', 430, 'IB3Va6d', '', TRUE, stir_fired_seafood_id),
  //   //     ('泰式檸檬蝦', 450, 'M0ahH1y', '', FALSE, stir_fired_seafood_id),
  //   //     ('清蒸鱈魚', 300, 'WlrefLh', '', FALSE, stir_fired_seafood_id),
  //   //     ('豆酥鱈魚', 300, '5KFmwi0', '', TRUE, stir_fired_seafood_id),
  //   //     ('橙汁鱸魚片', 240, 'FloObJR', '使用產銷履歷鱸魚', FALSE, stir_fired_seafood_id),
  //   //     ('糖醋鱸魚片', 240, 'hU8pi6w', '使用產銷履歷鱸魚', FALSE, stir_fired_seafood_id),
  //   //     ('蔥燒炒蟹', 450, 'aLpG8RV', '', FALSE, stir_fired_seafood_id),
  //   //     ('避風塘炒蟹', 450, 'F6q33Oq', '', TRUE, stir_fired_seafood_id),
  //   //     ('炒蛤仔', 190, 'DaCJyLi', '', FALSE, stir_fired_seafood_id),
  //   //     ('泰式椒麻雞', 250, 'X8gDZhq', '', TRUE, deep_fried_id),
  //   //     ('鹽酥蝦', 280, 'HtWIwOh', '使用產銷履歷蝦', FALSE, deep_fried_id),
  //   //     ('鹽酥龍珠', 210, 'BFiSJmV', '', FALSE, deep_fried_id),
  //   //     ('鳳梨蝦球', 290, 'P319wQy', '', TRUE, deep_fried_id),
  //   //     ('脆皮炸肥腸', 225, 'bGT0QCk', '肉品原產地：歐洲豬肉', FALSE, deep_fried_id),
  //   //     ('蚵仔酥', 210, '5ndxhok', '', FALSE, deep_fried_id),
  //   //     ('椒鹽大草蝦', 450, 'sCrFP3L', '', FALSE, deep_fried_id),
  //   //     ('五味炸豆腐', 150, '9S2kCGb', '', FALSE, deep_fried_id),
  //   //     ('酥炸三鮮(蝦仁、花枝、蚵仔)', 300, 'x7iKjVg', '使用產銷履歷白蝦', FALSE, deep_fried_id),
  //   //     ('酥炸絲瓜', 180, 'wT7Eu2v', '使用產銷履歷絲瓜', FALSE, deep_fried_id),
  //   //     ('爆漿熔岩蝦球(7粒)', 270, 'EZU3jx3', '', FALSE, deep_fried_id),
  //   //     ('鹽酥中卷', 280, 'RUsdVp9', '', FALSE, deep_fried_id),
  //   //     ('三杯雞', 250, 'PMJxWsQ', '', TRUE, three_cups_id),
  //   //     ('三杯中卷', 280, 'CwPsPFy', '', TRUE, three_cups_id),
  //   //     ('三杯豬肝', 200, 'lLHnkbP', '肉品原產地：臺灣豬肉', FALSE, three_cups_id),
  //   //     ('三杯皮蛋', 200, 'sTDShDY', '', FALSE, three_cups_id),
  //   //     ('三杯田雞', 300, 'PMJxWsQ', '', FALSE, three_cups_id),
  //   //     ('鐵板牛柳', 280, 'O2lA6DS', '肉品原產地：澳洲', TRUE, iron_plate_id),
  //   //     ('鐵板豆腐', 230, 'RKTMoCL',  '肉品原產地：臺灣豬肉', FALSE, iron_plate_id),
  //   //     ('鐵板蚵仔', 250, 'U3gH6Gx',  '', FALSE, iron_plate_id),
  //   //     ('鐵板豬肝', 200, 'FLcNKnK', '肉品原產地：臺灣豬肉', FALSE, iron_plate_id),
  //   //     ('五更腸旺', 250, '3WylZFD',  '肉品原產地：歐洲豬肉', TRUE, claypot_id),
  //   //     ('茄子腸煲', 270, 'xI6vzKW',  '肉品原產地：歐洲豬肉', FALSE, claypot_id),
  //   //     ('茄子雞煲', 280, 'qk6xz1X',  '', FALSE, claypot_id),
  //   //     ('花雕雞煲', 300, 'nLqfV00',  '', TRUE, claypot_id),
  //   //     ('炒高麗菜', 135, 'smxPOF5',  '豬脂(油)原產地：臺灣豬肉', TRUE , vegetables_id),
  //   //     ('炒空心菜', 135, 'Mo2WtUy',  '豬脂(油)原產地：臺灣豬肉', FALSE, vegetables_id),
  //   //     ('炒水蓮菜', 180, 'CXBOe4K',  '肉品原產地：臺灣豬肉', FALSE, vegetables_id),
  //   //     ('杞子炒川七', 160, 'L4aEIfl',  '', FALSE, vegetables_id),
  //   //     ('紅燒茄子', 160, '0ckynd2',  '肉品原產地：臺灣豬肉', FALSE, vegetables_id),
  //   //     ('皮蛋地瓜葉', 195, 'Y0HjFNC',  '肉品原產地：臺灣豬肉', FALSE, vegetables_id),
  //   //     ('燙地瓜葉', 160, 'VcXePn9',  '肉品原產地：臺灣豬肉', TRUE , vegetables_id),
  //   //     ('乾煸四季豆', 185, '7defArj',  '肉品原產地：臺灣豬肉', FALSE, vegetables_id),
  //   //     ('炒菠菜', 150, 'JAjbuYr',  '', FALSE, vegetables_id),
  //   //     ('薑絲鱸魚湯(大)', 380, 'q0H6LYD', '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('薑絲鱸魚湯(中)', 200, 'q0H6LYD', '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('薑絲鱸魚湯(小)', 110, 'q0H6LYD', '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('味噌鱸魚湯(大)', 380, 'VMaT4pZ',  '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('味噌鱸魚湯(中)', 200, 'VMaT4pZ',  '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('味噌鱸魚湯(小)', 110, 'VMaT4pZ',  '使用產銷履歷鱸魚', FALSE, soup_id),
  //   //     ('蛤蠣湯(大)', 355, 'D1DTujm', '', TRUE, soup_id),
  //   //     ('蛤蠣湯(中)', 185, 'D1DTujm', '', TRUE, soup_id),
  //   //     ('蛤蠣湯(小)', 100, 'D1DTujm', '', TRUE, soup_id),
  //   //     ('蚵仔湯(大)', 355, 'ThJxTpe', '', FALSE, soup_id),
  //   //     ('蚵仔湯(中)', 185, 'ThJxTpe', '', FALSE, soup_id),
  //   //     ('蚵仔湯(小)', 100, 'ThJxTpe', '', FALSE, soup_id),
  //   //     ('豬肝湯(大)', 260, 'tcfXl1H', '肉品原產地：臺灣豬肉', FALSE, soup_id),
  //   //     ('豬肝湯(中)', 130, 'tcfXl1H', '肉品原產地：臺灣豬肉', FALSE, soup_id),
  //   //     ('豬肝湯(小)', 80, 'tcfXl1H', '肉品原產地：臺灣豬肉', FALSE, soup_id),
  //   //     ('番茄豆腐蛋花湯(大)', 260, '5s8SPsY', '', FALSE, soup_id),
  //   //     ('番茄豆腐蛋花湯(中)', 130, '5s8SPsY', '', FALSE, soup_id),
  //   //     ('番茄豆腐蛋花湯(小)', 80, '5s8SPsY', '', FALSE, soup_id),
  //   //     ('白飯', 20, '8SCHjC3', '168g，每滿＄200有贈送1碗白飯(不包含炒飯麵、白飯及運費)，請再結帳頁面的附註上說明。這邊提供額外加點的服務', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('小菜毛豆', 50, 'i12sqQ2', '', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('聖沛黎洛 天然氣泡水', 100, 'oh8c7Sz', '750ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('老北京御品酸梅湯', 100, 'c2aHnqh', '900ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('愛之味麥仔茶', 60, 'Jt3lPiL', '990ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('御茶園日式綠茶', 60, 'o5iYRG1', '980ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('蘋果西打', 50, '2xwiLsb', '600ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('可口可樂', 50, 'tCtv3RT', '600ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('半天水椰子汁', 70, 'SyBYQ6i', '520ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('泰山冰鎮紅茶', 60, 'F313swt', '900ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('優鮮沛蔓越莓', 60, 'Ws6HMk5', '900ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('Sunkist芭樂汁', 60, 'QsP5Doe', '900ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('Sunkist柳橙汁', 60, 'bBbhE3z', '900ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('蜂蜜檸檬(小)', 130, 'AFPd5lP', '500ml', FALSE, a_la_carte_non_alcoholic_id),
  //   //     ('蜂蜜檸檬(大)', 200, 'uIoIQXg', '800ml', FALSE, a_la_carte_non_alcoholic_id);
  //   //   END $$;
  //   // `,
  // ]);
}
