// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project point_pro {
  database_type: 'PostgreSQL'
  Note: 'Food ordering and reservation system'
}

Enum "role" {
  "CUSTOMER"
  "STAFF"
  "ADMIN"
}

Enum "gender" {
  "MALE"
  "FEMALE"
  "OTHER"
}

Enum "log_type" {
  "LOGIN"
  "LOGOUT"
}

Enum "selection_type" {
  "SINGLE"
  "MULTIPLE"
}

Enum "order_status" {
  "WORKING"
  "FINISHED"
  "CANCEL"
}

Enum "order_type" {
  "DINE_IN"
  "TAKE_OUT"
}

Enum "payment_status" {
  "UNPAID"
  "SUCCESS"
  "CANCEL"
}

Enum "reservation_type" {
  "ONLINE"
  "PHONE"
}

Enum "slot_status" {
  "AVAILABLE"
  "FULL"
  "UNAVAILABLE"
}

Table "users" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "username" VARCHAR(50) [not null]
  "phone" VARCHAR(20) [unique, not null]
  "email" VARCHAR(100) [unique]
  "gender" gender
  "password_hash" VARCHAR(255)
  "role" ROLE [default: "CUSTOMER"]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "walk_in_users" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "people" SMALLINT [default: 1]
  "start_at" TIMESTAMPTZ
  "end_at" TIMESTAMPTZ
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "login_logs" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "log_type" log_type [default: "LOGIN"]
  "operation_time" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "user_id" UUID [not null]
}

Table "categories" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "title" VARCHAR(50) [unique, not null]
  "position" SMALLINT [default: 0]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "meals" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "title" VARCHAR(50) [unique, not null]
  "cover_url" VARCHAR(255) [default: ""]
  "description" TEXT [default: ""]
  "is_popular" BOOLEAN [default: FALSE]
  "price" INTEGER [default: 0]
  "position" SMALLINT [default: 0]
  "published_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "category_id" UUID
}

Table "specialties" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "title" VARCHAR(50) [unique, not null]
  "selection_type" selection_type [default: "SINGLE"]
  "position" SMALLINT [default: 0]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "specialty_items" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "title" VARCHAR(50) [unique, not null]
  "price" INTEGER [default: 0]
  "position" SMALLINT [default: 0]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "specialty_id" UUID
}

Table "meal_specialties" {
  "meal_id" UUID [not null]
  "specialty_id" UUID [not null]

  Indexes {
    (meal_id, specialty_id) [pk]
  }
}

Table "meal_specialty_items" {
  "meal_id" UUID [not null]
  "specialty_item_id" UUID [not null]

  Indexes {
    (meal_id, specialty_item_id) [pk]
  }
}

Table "payments" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "payment_no" TEXT [unique]
  "price" INTEGER [not null]
  "gateway" VARCHAR(50) [not null]
  "status" payment_status [default: "UNPAID"]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "periods" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "start_time" TIMESTAMPTZ [not null]
  "end_time" TIMESTAMPTZ [not null]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "reservations" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "type" reservation_type [default: "ONLINE"]
  "is_cancelled" BOOLEAN [default: FALSE]
  "people" SMALLINT [default: 1]
  "start_at" TIMESTAMPTZ
  "end_at" TIMESTAMPTZ
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "user_id" UUID [not null]
  "period_id" UUID [not null]
}

Table "seats" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "seat_no" VARCHAR(5) [unique, not null]
  "capacity" SMALLINT [not null]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
}

Table "period_seats" {
  "period_id" UUID
  "seat_id" UUID

  Indexes {
    (period_id, seat_id) [pk]
  }
}

Table "reservation_period_seats" {
  "reservation_id" UUID [not null]
  "period_id" UUID [not null]
  "seat_id" UUID [not null]

  Indexes {
    (reservation_id, period_id, seat_id) [pk]
  }
}

Table "orders" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "status" order_status [default: "WORKING"]
  "type" order_type [default: "DINE_IN"]
  "created_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "updated_at" TIMESTAMPTZ [default: `CURRENT_TIMESTAMP`]
  "walk_in_user_id" UUID
  "user_id" UUID
  "reservation_id" UUID
  "payment_id" UUID
}

Table "order_meals" {
  "id" UUID [pk, default: `uuid_generate_v4()`]
  "amount" SMALLINT [not null]
  "served_amount" SMALLINT [default: 0]
  "order_id" UUID [not null]
  "meal_id" UUID [not null]
}

Table "order_meal_specialties" {
  "order_meal_id" UUID [not null]
  "specialty_id" UUID [not null]

  Indexes {
    (order_meal_id, specialty_id) [pk]
  }
}

Table "order_meal_specialty_items" {
  "order_meal_id" UUID [not null]
  "specialty_item_id" UUID [not null]

  Indexes {
    (order_meal_id, specialty_item_id) [pk]
  }
}

Ref:"users"."id" < "login_logs"."user_id" [delete: cascade]

Ref:"categories"."id" < "meals"."category_id" [delete: set null]

Ref:"specialties"."id" < "specialty_items"."specialty_id" [delete: set null]

Ref:"meals"."id" < "meal_specialties"."meal_id" [delete: cascade]

Ref:"specialties"."id" < "meal_specialties"."specialty_id" [delete: cascade]

Ref:"meals"."id" < "meal_specialty_items"."meal_id" [delete: cascade]

Ref:"specialty_items"."id" < "meal_specialty_items"."specialty_item_id" [delete: cascade]

Ref:"users"."id" < "reservations"."user_id" [delete: cascade]

Ref:"periods"."id" < "reservations"."period_id" [delete: cascade]

Ref:"periods"."id" < "period_seats"."period_id" [delete: cascade]

Ref:"seats"."id" < "period_seats"."seat_id" [delete: cascade]

Ref:"reservations"."id" < "reservation_period_seats"."reservation_id" [delete: cascade]

Ref:"period_seats".("period_id", "seat_id") < "reservation_period_seats".("period_id", "seat_id") [delete: cascade]

Ref:"walk_in_users"."id" < "orders"."walk_in_user_id" [delete: set null]

Ref:"users"."id" < "orders"."user_id" [delete: set null]

Ref:"reservations"."id" < "orders"."reservation_id" [delete: set null]

Ref:"payments"."id" < "orders"."payment_id" [delete: set null]

Ref:"orders"."id" < "order_meals"."order_id" [delete: cascade]

Ref:"meals"."id" < "order_meals"."meal_id" [delete: cascade]

Ref:"order_meals"."id" < "order_meal_specialties"."order_meal_id" [delete: cascade]

Ref:"specialties"."id" < "order_meal_specialties"."specialty_id" [delete: cascade]

Ref:"order_meals"."id" < "order_meal_specialty_items"."order_meal_id" [delete: cascade]

Ref:"specialty_items"."id" < "order_meal_specialty_items"."specialty_item_id" [delete: cascade]
